# Code Reading

def full_name(first_name, last_name, title)
  # Example comment line

  # initializes variable "name" without a value
  name = nil

  # if "title" and "first_name" and "last_name" have values
  if title && first_name && last_name
    # assign "title", "first_name", and "last_name" to "name" with spaces between each value
    name = title + " " + first_name + " " + last_name
  # if only "title" and "last_name" have values
  elsif title && last_name
    # assign "title" and "last_name" to "name" with spaces between those values
    name = title + " " + last_name
  # if only "first_name" and "last_name" have values
  elsif first_name && last_name
    # assign "first_name" and "last_name" to "name" with a space in between
    name = first_name + " " + last_name
  # if only "first_name" has a value
  elsif first_name
    # set "name" to equal "first_name"
    name = first_name
  # if none of the above are true
  else
    # handle that error bro
    raise "Oh no, that doesn't look like a name"
  # end
  end

  # return the value "name" generated by the method
  return name
  # end
end

# Fix Broken Code

def full_name(first_name, last_name)
  return first_name + " " + last_name
end

puts full_name("bubba", "chuck")


# Coding


## Enter your code for your 'add' method below

def add(number_1, number_2)
  return number_1 + number_2
end

puts "Three tests"

puts add(1,2)
puts add(5,10)
puts add(4,4)

## Enter the code for you 'join_strings' method below

def join_strings(string_1, string_2)
  return string_1.to_s + " " + string_2.to_s
end

puts "Four tests"

puts join_strings("deez", "nuts")
puts join_strings(1,2)
puts join_strings(false, "false")
puts join_strings([1,"2",true], 2.5)

## Enter your 'old_enough_to_vote?' method below

def old_enough_to_vote(birth_year)
  if birth_year < 1998
    return "You are old enough to vote!"
  elsif birth_year == 1998
    return "You may be old enough to vote, depending on when your birthday is."
  else
    return "You are not old enough to vote!"
  end
end

puts "Two tests"

puts old_enough_to_vote(1997)
puts old_enough_to_vote(1998)
puts old_enough_to_vote(1999)